config/routes.rb
Rails.application.routes.draw do
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  root "users#new"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users
  resources :searches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  mount_uploaders :pictures, PicturesUploader

  def self.search(search)
    if search
      where("title ILIKE ?", "%#{search}%")
    end
  end

end

app/models/search.rb
class Search < ApplicationRecord
  def items
    @items ||= find_items
  end

  private
  def find_items
    items = Item.order(:title)
    items = items.where("title LIKE?", "%#{keywords}%") if keywords.present?
    items = items.where(category: category_id) if category_id.present?
    items = items.where("price >= ?", min_price) if min_price.present?
    items = items.where("price <= ?", max_price) if min_price.present?
    items
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password :validations => false
  has_many :authentications, dependent: :destroy
  has_many :items, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true


  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = User.create!(name: auth_hash["extra"]["raw_info"]["name"], email: auth_hash["extra"]["raw_info"]["email"])
    user.authentications << authentication
    return user
  end

  # grab fb_token to access Facebook for user data
  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

  # def correct_user
  #   @user = User.find(params[:id])
  #   redirect_to(root_url) unless current_user?(@user)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]


  # GET /items
  # GET /items.json


  def index
    if params[:search]
      @items = Item.search(params[:search])
    else
      @items = Item.all
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :category_id, :condition, :price, :location, :user_id,  {pictures: []})
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
  end

  def create

    @search = Search.new(search_params)
    @search.save
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private

  def search_params
    params.require(:search).permit(:keywords, :category_id, :min_price, :max_price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(session[:user_id])
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

  def create_from_omniauth
     auth_hash = request.env["omniauth.auth"]
     authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

     # if: previously already logged in with OAuth
     if authentication.user
       user = authentication.user
       authentication.update_token(auth_hash)
       @next = items_path
       @notice = "Signed in!"
     # else: user logs in with OAuth for the first time
     else

       user = User.create_with_auth_and_hash(authentication, auth_hash)
       # you are expected to have a path that leads to a page for editing user details

       @next = edit_user_path(user.id)
       @notice = "User created. Please confirm or edit details"
     end
     session.clear
     session[:email] = user.email
     session[:name] = user.name
     session[:user_id] = user.id
     signup_url(user)
     redirect_to @next, :notice => @notice
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :correct_user, only: [:edit, :update, :delete]

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(session[:user_id])
    else
      render 'users/new'
    end
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to @user, notice: "updated"
    else
      redirect_to @user, notice: "failed"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
   user = User.find(current_user.id)
   user.destroy
   reset_session
   flash[:notice] = "User destroyed."
   redirect_to '/'
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_all_item.html.erb
<table>
  <thead>
    <tr>
      <th>title</th>
      <th>location</th>
      <th>Price</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= items.title %></td>
        <td><%= items.location %></td>
        <td><%= items.price %></td>
        <% if items.pictures? %>
        <td><%= image_tag items.pictures.first.thumb %>
          <% else %>
          <td> no picture </td>
          <% end %>
        <td><%= link_to 'Show', items %></td>
        <td><%= link_to 'Edit', edit_item_path(items) %></td>
        <td><%= link_to 'Destroy', items, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="filed">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :condition %>
    <%= f.text_field :condition %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <%= f.file_field :pictures, multiple: true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<table>
  <thead>
    <tr>
      <th>title</th>
      <th>description</th>
      <th>location</th>
      <th>Price</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.location %></td>
        <td><%= item.price %></td>
        <% if item.pictures? %>
        <td>
          <%  item.pictures.each do |x| %>
          <%= image_tag x.normal %>
          <% end %>
          <% else %>
          <td> no picture </td>
          <% end %>
      </tr>
  </tbody>
</table>

<h2>Seller Info</h2>
<p>Email address: <%= item.user.email %><p>

app/views/items/_search_results.html.erb
<% if items.present? %>
<% items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><%= item.location %></td>
      <td><%= item.price %></td>
      <% if item.pictures? %>
      <td><%= image_tag item.pictures.first.thumb %>
        <% else %>
        <td> no picture </td>
        <% end %>
        <td><%= link_to 'Show', item %></td>
        <% if current_user.id == item.user.id %>

      <td><%= link_to 'Edit', edit_item_path(item) %></td>
      <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  <% end %>
  <% else %>
  <p> no result found <p>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
</div>
<h1>Item</h1>

<%= form_tag items_path, :method => 'get', remote: true do %>
  <p>
    <input type="text_field" placeholder="Search For Items Title" name="search">
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<%= link_to "Advanced Search", new_search_path %>
<div>
  <table>
    <thead>
      <tr>
        <th>title</th>
        <th>location</th>
        <th>Price</th>
        <th>Picture</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody id='all_items'>
      <%= render partial: 'search_results', locals: {items: @items} %>
    </tbody>
  </table>

</div>


<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/index.js.erb
$('#all_items').html("<%=  escape_javascript(render :partial => 'search_results', locals: {items: @items}) %>")

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<%= render 'item', item: @item %>
<%= link_to 'Back To Itemlist', items_path %>
<% if @item.user.id == current_user.id %>
<%= link_to 'Edit', edit_item_path(@item) %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuyAndSell</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  <body>
    <!-- jQuery before Propeller.js -->

    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <% if current_user %>

      Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %> | <%= link_to "Edit your profile", edit_user_path(current_user.id)%> | <%= link_to "Show Itemlist", items_path %>
      <div>
      <% flash.each do |message_type, message| %>
      <p><%= message %></p>
      <% end %>
    </div>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %> | <%= link_to "Sign in with Facebook", "/auth/facebook" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/searches/new.html.erb
<h1> Advanced Search </h1>
<%= form_for @search do |f| %>
 <div class="filed">
   <%= f.label :keywords %>
   <%= f.text_field :keywords %>
 </div>

 <div class="filed">
   <%= f.label :category_id %>
   <%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true %>
 </div>

 <div class="filed">
   <%= f.label :min_price, "Price Range" %>
   <%= f.number_field :min_price %> -
   <%= f.number_field :max_price %>
 </div>

 <div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/searches/show.html.erb
<h1> Search Results </h1>
<% if @search.items.present? %>
<h2> <%= @search.items.count %> results found <h2>
<%= render @search.items %>
<% else %>
<p> no result found <p>
  <% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>


<%= form_for @user do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  <%= f.submit "Update Info" %>

<% end %>

<%= link_to "delete", user_path(current_user), method: :delete %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<% @user.errors.full_messages.each do |y| %>
<p><%= y %></p>
<% end %>

<%= form_for @user do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="filed">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div class="filed">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div class="filed">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<p> hi, <%= current_user.email %> </p>